const fs = require('fs');
const path = require('path');
const outDir = path.join(__dirname, '..', 'public');
const outFile = path.join(outDir, 'favicon.ico');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
const size = 70;
const ico = Buffer.alloc(size);
let o = 0;
ico.writeUInt16LE(0, o); o += 2;
ico.writeUInt16LE(1, o); o += 2;
ico.writeUInt16LE(1, o); o += 2;
ico.writeUInt8(16, o); o += 1;
ico.writeUInt8(16, o); o += 1;
ico.writeUInt8(0, o); o += 1;
ico.writeUInt8(0, o); o += 1;
ico.writeUInt16LE(1, o); o += 2;
ico.writeUInt16LE(32, o); o += 2;
ico.writeUInt32LE(62, o); o += 4;
ico.writeUInt32LE(22, o); o += 4;
ico.writeUInt32LE(40, o); o += 4;
ico.writeInt32LE(1, o); o += 4;
ico.writeInt32LE(2, o); o += 4;
ico.writeUInt16LE(1, o); o += 2;
ico.writeUInt16LE(32, o); o += 2;
ico.writeUInt32LE(0, o); o += 4;
ico.writeUInt32LE(0, o); o += 4;
ico.writeUInt32LE(0, o); o += 4;
ico.writeUInt32LE(0, o); o += 4;
ico.writeUInt32LE(0, o); o += 4;
ico.writeUInt32LE(0, o); o += 4;
ico.writeUInt32LE(0x00ffffff, o); o += 4;
ico.writeUInt32LE(0xff000000, o);
fs.writeFileSync(outFile, ico);
console.log('favicon.ico written to public/');
